### ISSUE TITLE
Polish rss feed 

### ISSUE THREAD

**Issue by Gankra** [request-for-explanation/podcast#13]
<img width="987" alt="screen shot 2017-06-19 at 11 00 09 pm" src="https://user-images.githubusercontent.com/1136864/27314638-2cb1c7ce-5543-11e7-80f1-c7a224450ec4.png">

**Comment by frewsxcv** [comment]
If for any reason you're looking for a crate for this: https://github.com/rust-syndication/rss/

**Comment by Manishearth** [comment]
Also, the show notes should be in the feed.

We should script this.

**Comment by dzamlo** [comment]
Another thing to add to the feed would be the episodes duration.

**Comment by LinusCDE** [comment]
Also please add a publish date to your last episode (11).
My rss reader (university project; self-hosted) project got tripped by that and wouldn't let me add the podcast because of database constraints (needs date).
I currently monkey patched that to use Unix time 0 instead, but I haven't pushed that change since I consider a publish date to be vital.

![error image](https://user-images.githubusercontent.com/22298664/89115940-803ac080-d48e-11ea-9b27-b4f6b90376dc.png)

The error message translates to: The podcast could not be added. Is the URL valid?

**Comment by Manishearth** [comment]
@LinusCDE I'd accept a PR doing this, I'm not actively maintaining this otherwise, sorry

**Comment by LinusCDE** [comment]
Uh, didn't notice that the entire webpage is actually open source.
Seems that you already fixed it anyway by adding a `<pubDate>`-Tag to the recent epiode along with the new episode.

**Comment by LinusCDE** [comment]
I have looks at the `rss.xml` file and it seems that the issues from the initial screenshot are already addressed. So I don't see any reason for this issue to still be open.
