### ISSUE TITLE
Episode about what an RFC is

### ISSUE THREAD

**Issue by carols10cents** [request-for-explanation/podcast#8]
Should we do an episode talking about the RFC process? Or should we just point to the RFC repo README?

**Comment by Manishearth** [comment]
This would be super fun. We can also include anecdotes about old rfcs.

Especially the Integer Debate that formed the current form of this process.

On Jun 18, 2017 2:12 PM, "Carol (Nichols || Goulding)" <
notifications@github.com> wrote:

Should we do an episode talking about the RFC process? Or should we just
point to the RFC repo README?

—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub
<https://github.com/request-for-explanation/podcast/issues/8>, or mute the
thread

**Comment by Manishearth** [comment]
From #21

> I've been writing rust for a few months now, and something I've had trouble sorting out from following the RFCs is the overall lifecycle. I've been following discussions on many RFCs, but am yet to see anything go from RFC to usable in the toolchain. I'm sure it'll become clear in time, but being new to the community, I'd love some insight on this from folks involved in the process.
> 
> I was hoping you'd like to discuss the RFC process, and what happens to an RFC once it's accepted. How does the work get done? What is the process for promotion through nightly, beta, stable?
> 
> Perhaps this is too high level for the podcast, and that's fine, but I thought I'd pitch the idea just in case!
> 
> Cheers,
> Owen

**Comment by carols10cents** [comment]
DONE! https://request-for-explanation.github.io/podcast/ep3-aarons-favorite-topic/index.html
